# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 6dd7c97bd0a90af01189f4decc3cf7ba600b7442b6b7c5553baf32189ac4e6ddda6d39cf82184c323dcf35b7e165234817ead4a2e10a7a3053aa12ad4a42192e

test:
  secret_key_base: bdf477d1add5c6ef8c766ee40f6c233de6a2d8ab21a6c7c5b77ffc028685cf3f016ba28bda3824cefe0c97be21a038c85bac74dc4f4b7dda2b813e008d39ba3b

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
